name: Terraform Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ github.repository }}-terraform
  cancel-in-progress: true

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ./infra

    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v5.1.1
       with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

     - name: Set up Terraform
       uses: hashicorp/setup-terraform@v4
       with:
          terraform_version: 1.15.7
     
     - name: Terraform Init
       run: terraform init

     - name: terraform validate
       run: terraform validate

     - name: tflint
       uses: terraform-linters/setup-tflint@v6
       with:
         tflint_version: 0.52.0
         cache: true

     - name: Init TFLint
       run: tflint --init
       env:
          GITHUB_TOKEN: ${{ github.token }}
     
     - name: run tflint
       run: tflint -f compact

     - name: checkov scan
       uses: bridgecrewio/checkov-action@v12
       with:
         directory: ./infra
         framework: terraform
         severity-threshold: medium
         soft_fail: true
      
     - name: Terraform Plan
       id: plan
       run: terraform plan -out=tfplan

     - name: Terraform Apply
       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
       run: terraform apply -auto-approve tfplan