name: build and push docker image to ECR

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'app/**'

concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
    build:
        runs-on: ubuntu-latest

        env:
          ECR_REPOSITORY: threatapp_repo
          AWS_ACCOUNT_ID: 666709165403
          IMAGE_TAG: ${{ github.sha }}
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v5.1.1
          with:
            role-to-assume: ${{ vars.AWS_ROLE_ARN }}
            aws-region: ${{ vars.AWS_REGION }}

        - name: Login to Amazon ECR
          uses: aws-actions/amazon-ecr-login@v2

        - name: Build image
          run: |
            docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

        - name: Scan image for vulnerabilities
          uses: aquasecurity/trivy-action@v0.36.0
          with:
            image-ref: ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
            format: 'table'
            exit-code: '0'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'

        - name: Tag image
          run: |
            docker tag $ECR_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

        - name: Push image
          run: |
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

        - name: Add github sha to SSM. Used by terraform to deploy the latest image
          uses: dwardu89/aws-ssm-parameter-store@v2
          with:
            ssm-path: "/OIDC/image_tag"
            ssm-value: ${{ github.sha }}
            aws-region: ${{ vars.AWS_REGION }}
            ssm-value-type: "String"
            ssm-value-overwrite: true
